version: "3.5"

services:

  # a transaction processor for the XO demo
  # we are using local code for this so we can edit it
  voting-tp:
    build:
      context: ../voting
    container_name: sawtooth-voting-tp
    depends_on:
      - validator
    networks:
      - sawtooth-dev
    # mount the code for our tp into the container
    # this makes it easy to edit the code on our computer
    # without having to rebuild the container image each time
    # also mount the keys from the shell container so we can
    # read the keys for submitting transactions from the CLI
    volumes:
      - ../voting/src:/app/src
      - ./.keys:/root/.sawtooth/keys
    # loop forever so we can manually enter the container to run the tp
    # this is useful for development where we want to restart the tp
    # after having made code changes
    entrypoint: tail -f /dev/null
