version: "3.5"

services:

  # a transaction processor for the XO demo
  # we are using local code for this so we can edit it
  xo-tp:
    build:
      context: ../xo-javascript
    container_name: sawtooth-xo-javascript-default
    depends_on:
      - validator
    networks:
      - sawtooth-dev
    # mount the code for our tp into the container
    # this makes it easy to edit the code on our computer
    # without having to rebuild the container image each time
    # also mount the keys from the shell container so we can
    # read the keys for submitting transactions from the CLI
    volumes:
      - ../xo-javascript/src:/app/src
      - ./.keys:/root/.sawtooth/keys
    # loop forever so we can manually enter the container to run the tp
    # this is useful for development where we want to restart the tp
    # after having made code changes
    entrypoint: bash -c 'while true; do sleep 1; done'

  # a web UI frontend for the xo tp
  # it will communicate to the TP via the sawtooth rest api
  xo-demo:
    image: blockchaintp/xo-demo:master
    container_name: sawtooth-xo-demo
    networks:
      - sawtooth-dev
    ports:
      - "8081:80"
    depends_on:
      - validator
    environment:
      - REST_API_HOSTNAME=rest-api
      - REST_API_PORT=8008


